name: "CI"

on:
  pull_request:
    branches: [$default-branch]
  push:
    branches: [$default-branch]

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache NPM
        uses: octanner/cache-action@v1
        with:
          package-manager: "npm"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      # Use a dedicate step for installing dependencies
      # This makes troubleshooting caching easier
      - name: Install Dependencies
        run: npm install --nofund # DO NOT use `clean install` as it wipes out the cache-action

      - name: Run Tests
        run: npm run test
