name: "CI"

on:
  pull_request:
    branches: [$default-branch]
  push:
    branches: [$default-branch]

# Permissions needed for EnricoMi test results publishing
permissions:
  contents: read
  checks: write
  pull-requests: write

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      OCT_VAULT_SHARED_READ_ARTIFACTORY_PASSWORD: ${{ secrets.OCT_VAULT_SHARED_READ_ARTIFACTORY_PASSWORD }}
      OCT_VAULT_SHARED_READ_ARTIFACTORY_USERNAME: ${{ secrets.OCT_VAULT_SHARED_READ_ARTIFACTORY_USERNAME }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Sbt
        uses: octanner/cache-action@v1
        with:
          package-manager: "sbt"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "21"

      - name: Setup Sbt
        uses: sbt/setup-sbt@v1

      # Use a dedicate step for installing dependencies
      # This makes troubleshooting caching easier
      - name: Download Dependencies
        run: sbt update

      - name: test:compile
        run: sbt test:compile

      - name: Run Tests and Generate Coverage Report and Aggregate
        run: sbt coverage test coverageReport coverageAggregate

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()  # Run even if tests fail
        with:
          files: "target/test-reports/**/*.xml"
          check_name: "Test Results"
          comment_mode: always
          compare_to_earlier_commit: true
          report_individual_runs: true
          check_run_annotations: "all tests"
          job_summary: true

      - name: Upload Coverage to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
